package:
  format-version: "1.0.0"
  name: "core_apps_sam_l22"
  version: "dev"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "dev"
    - name: "dev_packs"
      type: "package"
      version: "dev"
    - name: "core"
      type: "package"
      version: "dev"
    - name: "usb"
      type: "package"
      version: "dev"